module.exports.descriptors = [
    'Acorn',
    'African',
    'American',
    'Ant',
    'Artic',
    'Army',
    'Banded',
    'Bark',
    'Bee',
    'Brown',
    'Bush',
    'Cherry',
    'Common',
    'Devils',
    'Desert',
    'Dung',
    'Elphant',
    'Easten',
    'Elm',
    'European',
    'False',
    'Fir',
    'Golden',
    'Giant',
    'Great',
    'Green',
    'Hag',
    'Herald',
    'Hermit',
    'House',
    'Horse',
    'Imperial',
    'Ivory',
    'Jewel',
    'Jumping',
    'Juniper',
    'Lace',
    'Leaf-footed',
    'Lily',
    'Little',
    'Long-horned',
    'Maple',
    'Mexican',
    'Miner',
    'Northern',
    'Oak',
    'Orb',
    'Painted',
    'Pale',
    'Paper',
    'Peacock',
    'Pleasing',
    'Potato',
    'Queen',
    'Rainbow',
    'Red',
    'Rice',
    'Rose',
    'Sand',
    'Scarlet',
    'Shadow',
    'Silver',
    'Small',
    'Snow',
    'Southern',
    'Tarantula',
    'Tiger',
    'Treehopper',
    'Twelve-spotted',
    'Unicorn',
    'Velvet',
    'Vivid',
    'Walnut',
    'Water',
    'Western',
    'White-fringed',
    'Wolf',
    'Widow',
    'Yellow',
    'Wood',
    'Zebra',
    'Zig-Zag'


]

module.exports.bugNames = [
    'Ant',
    'Bee',
    'Wasp',
    'Insect',
    'Beetle',
    'Butterfly',
    'Moth',
    'Dragonfly',
    'Damselfly',
    'Grasshopper',
    'Cricket',
    'Spider',
    'Tarantula',
    'True Bug',
    'Caddisfly',
    'Centipede',
    'Millipede',
    'Cicada',
    'Planthopper',
    'Cockroach',
    'Earwig',
    'Fly',
    'Mosquito',
    'Mantis',
    'Mite',
    'Scorpion',
    'Nymph',
    'Skipper',
    'Bumble Bee',
    'Cone-Nose',
    'Borer',
    'Snail',
    'Slug',
    'Stinkbug'


]

module.exports.sciName = [
    'Varanus sp.',
    'Tetracerus quadricornis',
    'Arctogalidia trivirgata',
    'Ardea cinerea',
    'Lutra canadensis',
    'Ceratotherium simum',
    'Morelia spilotes variegata',
    'Pteropus rufus',
    'Xerus sp.',
    'Francolinus swainsonii',
    'Phoeniconaias minor',
    'Delphinus delphis',
    'Uraeginthus granatina',
    'Tockus flavirostris',
    'Junonia genoveua',
    'Upupa epops',
    'Acanthaster planci',
    'Odocoileus hemionus',
    'Mazama gouazoubira',
    'Streptopelia decipiens',
    'Lamprotornis superbus',
    'Diomedea irrorata',
    'Agkistrodon piscivorus',
    'Vulpes cinereoargenteus',
    'Geochelone radiata',
    'Rhabdomys pumilio',
    'Pelecanus occidentalis',
    'Eolophus roseicapillus',
    'Tockus flavirostris',
    'Nasua nasua',
    'Suricata suricatta',
    'Theropithecus gelada',
    'Lasiodora parahybana',
    'Dasypus novemcinctus',
    'Libellula quadrimaculata',
    'Hystrix cristata',
    'Anthropoides paradisea',
    'Milvus migrans',
    'Geochelone elephantopus',
    'Chionis alba',
    'Iguana iguana',
    'Spilogale gracilis',
    'Phalacrocorax carbo',
    'Alcelaphus buselaphus cokii',
    'Recurvirostra avosetta',
    'Felis serval',
    'Ploceus rubiginosus',
    'Cygnus buccinator',
    'Elephas maximus bengalensis',
    'Alouatta seniculus',
    'Pavo cristatus',
    'Oryx gazella',
    'Limosa haemastica',
    'Naja haje',
    'Sarkidornis melanotos',
    'Laniarius ferrugineus',
    'Chloephaga melanoptera',
    'Odocoileus hemionus',
    'Erinaceus frontalis',
    'Hymenolaimus malacorhynchus',
    'Uraeginthus granatina',
    'Snycerus caffer',
    'Eumetopias jubatus',
    'Lepus townsendii',
    'Nycticorax nycticorax',
    'Agelaius phoeniceus',
    'Vulpes chama',
    'Platalea leucordia',
    'Heloderma horridum',
    'Threskionis aethiopicus',
    'Cracticus nigroagularis',
    'Eudyptula minor',
    'Psophia viridis',
    'Mazama gouazoubira',
    'Manouria emys',
    'Cyrtodactylus louisiadensis',
    'Creagrus furcatus',
    'Tauraco porphyrelophus',
    'Ovis dalli stonei',
    'Thalasseus maximus',
    'Bubulcus ibis',
    'Corvus albicollis',
    'Delphinus delphis',
    'Equus burchelli',
    'Amphibolurus barbatus',
    'Hyaena brunnea',
    'Dendrocitta vagabunda',
    'Dusicyon thous',
    'Ciconia episcopus',
    'Lamprotornis nitens',
    'Hippotragus equinus',
    'Lamprotornis nitens',
    'Acinynox jubatus',
    'Oreotragus oreotragus',
    'Lamprotornis nitens',
    'Dusicyon thous',
    'Lamprotornis superbus',
    'Alligator mississippiensis',
    'Lybius torquatus',
    'Kobus defassa',
    'Lorythaixoides concolor',
    'Pycnonotus nigricans',
    'Bubo sp.',
    'Mabuya spilogaster',
    'Sylvilagus floridanus',
    'Pelecanus conspicillatus',
    'Trichosurus vulpecula',
    'Lamprotornis sp.',
    'Camelus dromedarius',
    'Otocyon megalotis',
    'Caiman crocodilus',
    'Lybius torquatus',
    'Equus hemionus',
    'Vulpes vulpes',
    'Columba livia',
    'Cercatetus concinnus',
    'Otaria flavescens',
    'Felis rufus',
    'Bucorvus leadbeateri',
    'Macropus fuliginosus',
    'Phoeniconaias minor',
    'Petaurus norfolcensis',
    'Uraeginthus granatina',
    'Vulpes chama',
    'Agelaius phoeniceus',
    'Vanessa indica',
    'Antilocapra americana',
    'Trichoglossus chlorolepidotus',
    'Trichosurus vulpecula',
    'Lutra canadensis',
    'Dendrocitta vagabunda',
    'Cercopithecus aethiops',
    'Cercatetus concinnus',
    'Anhinga rufa',
    'Tyto novaehollandiae',
    'Spizaetus coronatus',
    'Phalacrocorax brasilianus',
    'Sciurus vulgaris',
    'Merops nubicus',
    'Cebus nigrivittatus',
    'Phalacrocorax brasilianus',
    'Climacteris melanura',

    'unavailable',
    'Ovis orientalis',
    'Lamprotornis nitens',
    'Ploceus rubiginosus',
    'Dacelo novaeguineae',
    'Haematopus ater',
    'Kobus defassa',
    'Lutra canadensis',
    'Boa constrictor mexicana',
    'Speotyte cuniculata',
    'Antilope cervicapra',
    'Castor fiber',
    'Macropus agilis',
    'Eudyptula minor',
    'Carduelis pinus',
    'Lamprotornis sp.',
    'Vanellus sp.',
    'Hymenolaimus malacorhynchus',
    'Bucephala clangula',
    'Dicrurus adsimilis',
    'Trichoglossus chlorolepidotus',
    'Suricata suricatta',
    'Caiman crocodilus',
    'Pycnonotus nigricans',
    'Tachyglossus aculeatus',
    'Ourebia ourebi',
    'Pteropus rufus',
    'Varanus salvator',
    'Microcavia australis',
    'Pseudoleistes virescens',
    'Larus dominicanus',
    'Uraeginthus granatina',
    'Manouria emys',
    'Milvago chimachima',
    'Tadorna tadorna',
    'Meleagris gallopavo',
    'Lepus arcticus',
    'Pteronura brasiliensis',
    'Ammospermophilus nelsoni',
    'Phoca vitulina',
    'Cochlearius cochlearius',
    'Castor fiber',
    'Lemur catta',
    'Macropus agilis',
    'Loxodonta africana',
    'Phoenicopterus chilensis',
    'Diomedea irrorata',
    'Trichosurus vulpecula',
    'Cordylus giganteus',
    'Tachybaptus ruficollis',
    'Cervus elaphus',
    'Zalophus californicus',
    'Callipepla gambelii',
    'Coracias caudata',
    'Procyon lotor',
    'Uraeginthus angolensis',
]

